### ISSUE TITLE
something wrong happend when catkin_make --pkg calibration_common

### ISSUE THREAD

**Issue by lewislongman** [iaslab-unipd/calibration_toolkit#1]
building CXX object ...../camera_model.cpp.o
In file included from /usr/include/eigen3/Eigen/Core:277:0,
                        from ....../calibration_common/base/matrix.h:33,
                        from ....../calibration_common/objects/globals.h:32,
                        ..........
                        ..........
/usr/include/eigen3/Eigen/src/Core/DenseBase.h: In instantiation of "......." 
/usr/include/eigen3/Eigen/src/Core/ArrayBase.h:  required from "......."
.......
/usr/include/pcl-1.7/pcl/imp/point_types.hpp: required from "......"
.......
....,,.
make[2]:**\* [calibration_toolkit/calibration_common/CMakeFiles/calibration_common.dir/src/calibration_common/pinhole/camera_model.cpp.o] error 1
make[1]:***[calibration_toolkit/calibration_common/CMakeFiles/calibration_common.dir/all error2

my environment is Ubuntu 12.04, gcc 4.8, ros hydro

can you help me

**Comment by bassofil** [comment]
Sorry, the package is lacking documentation.

I think the problem is that Eigen version in Ubuntu 12.04 is 3.0.x while the package needs at least Eigen 3.2.0. You can install it manually by following the instructions on the [website](http://eigen.tuxfamily.org/index.php?title=Main_Page).

Hope this helps,
Filippo
